blank_issues_enabled: true
contact_links:
    - name: GitHub Discussions
      url: https://github.com/upbots-org/.github/discussions
      about: Start a discussion
    - name: Discord support server
      url: https://discord.gg/upbots
      about: The best place to go for help installing or using WhackDevelopment's softwares.
